<table width="1163" border="1" cellspacing="3" cellpadding="3" fitColumns="true" id="horario">
	<tr>
		<th scope="col">HORAS</th>
		<th scope="col">LUNES</th>
		<th scope="col">MARTES</th>
		<th scope="col">MIERCOLES</th>
		<th scope="col">JUEVES</th>
		<th scope="col">VIERNES</th>
	</tr>
	<?php 
		foreach($this->horas as $hora){
			if($hora['hora'] == 'RECREO'){
				echo"<tr style='background-color:#6293BB;color:#fff; text-align:center'>
						<th colspan='6' scope='row'>RECREO</th>
					</tr>";
			}else{
				echo"<tr data-idhora='{$hora['id_hora']}' id='hora_{$hora['id_hora']}'><th scope='row'>{$hora['hora']}</th>";				
				foreach($this->datos as $dato){					
					if($hora['hora'] == $dato['hora']){						
						echo count($dato['dia']);
						echo"<td data-dia='{$dato['dia']}' data-idhora='{$hora['id_hora']}' class='drop droppable ocupado'>
								<a href='#' class='drag assigned-materia' data-idprofesor='{$dato['id_profesor']}' data-idmateria='{$dato['id_materia']}' title='Profesor: {$dato['nombre_profesor']}' style='position: static; left: 25px; top: 16px;'>
									{$dato['materia']}
								</a>
							 </td>";
					}
				}				
			}
		}
	?>
</table>