<?php 
$rutaImgane = Zend_Registry::get('config')->app->Imagenes;
$sessionPerfiles = new Zend_Session_Namespace('perfiles');
$perfil = $sessionPerfiles->perfil;

?>

<div class="easyui-panel" fit="true" border="false" style="height:100%;overflow:hidden">
    <div class="cart">
         <div class="ctitle"><?php echo 'Profesor: '.Zend_Auth::getInstance()->getIdentity()->S_NOMBRE;?></div>
        <div class="ctitle">
            <div class="contenedor-select-profesores" style="<?php if($perfil == 3){ echo"display:block;"; }else{ echo"display:none;";}?>">
                Profesor 
                <select id="profesores" name="profesores" onchange="cargar_combo('profesores','<?php echo $this->url(array('controller' => 'APG', 'action' => 'cargacombo'));?>','contenedor-select-grupos');">        			
        		<option value="">Selecciona...</option>
        		<?php
        		    					
        			foreach($this->listaCombo as $grupo){
                        echo"<option value='";
                        if (isset($_GET['idProfesor'])) {                            
                            if($grupo['id_profesor'] == $_GET['idProfesor']){
                            	echo $grupo['id_profesor']."' selected>".$grupo['nombre']."</option>";
                            }else{
                            	echo $grupo['id_profesor']."'>".$grupo['nombre']."</option>";
                            }
                        }else {
                            echo $grupo['id_profesor']."'>".$grupo['nombre']."</option>";                        	
                        }                   					
        				
        			}

        		
        		?> 
        		</select>
			</div>
			<div class="contenedor-select-grupos" style="<?php if($perfil == 3 && isset($_GET['idProfesor'])){ echo"display:block;"; }elseif($perfil == 3){ echo"display:none;"; }else{ echo"display:block;";}?>">
			     Grupos: 
    			<select id="grupos" name="grupos" onchange="cargar_combo('grupos','','carga_tabla');">    			  				
    			<?php
    			    if(!isset($_GET['idCombo'])){ echo"<option values=''>Selecciona..</option>";}   			 
    				foreach($this->listaCombo as $grupo){
                        echo"<option value='";
                        if(!isset($_GET['idCombo'])){                           
                            echo $grupo['id_grupo']."'>".$grupo['grupo']."</option>";                           
                        }
                        if (isset($_GET['idCombo'])) {
                        	if($grupo['id_grupo'] == $_GET['idCombo']){
                        		echo $grupo['id_grupo']."' selected>".$grupo['grupo']."</option>";
                        	}else{
                        		echo $grupo['id_grupo']."'>".$grupo['grupo']."</option>";
                        	}
                        }
    				}				
    			
    			?>
    			</select>
    		</div>
		</div>		
		<div id="contenedorTabla" style="<?php if ($this->validacion == 1) { echo "display:none;";}else{ echo "display:block";}?>">	
            <div class="ctitle">Materias</div>
            <div style="background:#fff" id="carga_tabla">
    		  <?php echo $this->render('APG/cargatabla.phtml'); ?>
    		 </div>           
    		<div class="elimina"></div>
    		<div class="botonera">
			<a class="easyui-linkbutton" data-options="iconCls:'icon-ok'" href="javascript:void(0)" onclick="genera_json()">Guardar</a>
		</div>		
	   </div>
	</div>
    <div class="products">
        <?php
				$contador_profesores = 1;
				$contador_materias = 1;
				echo '<ul id="menu_arbol">';
					foreach($this->arreglo as $llave_padres => $valor_padres){		
						$separa= explode('_',$llave_padres);
						if($contador_profesores == count($this->arreglo)){
							echo "<li class='cierre' id='padre_{$separa[1]}'>";
						}else{
							echo "<li id='padre_{$separa[1]}'>";
						}
						echo "<a href='#'>{$separa[0]}</a>";
						echo"<ul class='contenedor-hijos'>";
						foreach($valor_padres as $hijos_llave => $hijos_valor){
							if($contador_profesores > 1){
								$contador_materias=1;					
							}
							if($contador_materias == count($valor_padres)){
								echo"<li class='cierre'><a href='#' class='drag' data-idprofesor='{$separa[1]}' data-idmateria='{$hijos_valor['id_materia']}' title='Profesor: {$separa[0]}'>{$hijos_valor['nombre_materia']}</a></li>";	
							}else{
								echo"<li><a href='#' class='drag' data-idprofesor='{$separa[1]}' data-idmateria='{$hijos_valor['id_materia']}' title='Profesor: {$separa[0]}'>{$hijos_valor['nombre_materia']}</a></li>";					
								
							}
							$contador_materias++;				
						}
						echo"</ul>";
						echo "</li>";
						$contador_profesores++;	
					}
				echo '</ul>';
			?>
		
    </div>
	
	
</div>
<style type="text/css">
	.products{
		overflow:auto;
		height:100%;
		background:#fafafa;
		width:183px;
	}
	.cart{
		float:right;
		position:relative;
		width:1163px;
		height:100%;
		background:#ccc;
		padding:0px 10px;
	}
	.ctitle{
		text-align:center;
		color:#555;
		font-size:18px;
		padding:10px;
	}
	
	.cart .botonera{margin-top:30px; width:150px;}
	.elimina{
		position:absolute;
		width:150px;
		height:150px;
		background:url(<?php echo $rutaImgane.'/basura.jpg'?>) no-repeat scroll -133px 0 transparent;
		top: 401px;
		left: 622px;
	}
	.bote-rojo{
		background-position:13px 0;
	}}
</style>
<script>
$(function(){
    
	$('#menu_arbol ul').hide();
	$('#menu_arbol a').click(function(){
		$(this).next().slideToggle('fast');
		return false;
	});
	
	$('#menu_arbol li a.drag').draggable({
		revert:true,
		proxy:'clone',
		onStartDrag:function(){
			$(this).draggable('options').cursor = 'not-allowed';
			$(this).draggable('proxy').css('z-index',10);
		},
		onStopDrag:function(){
			$(this).draggable('options').cursor='move';
		}
	});
	$('#horario td.drop a').draggable({
		revert:true,
		proxy:'clone',
		onStartDrag:function(){
			$(this).draggable('options').cursor = 'not-allowed';
			$(this).draggable('proxy').css('z-index',10);
		},
		onStopDrag:function(){
			$(this).draggable('options').cursor='move';
		}
	});	
	$('#horario td.drop').droppable({
		onDragEnter:function(e,source){			
			$(source).draggable('options').cursor='auto';
			$(this).addClass('over');			
		},
		onDragLeave:function(e,source){			
			$(source).draggable('options').cursor='not-allowed';
			$(this).removeClass('over');			
		},
		onDrop:function(e,source){
			var id_grupo = $('#grupos').val();
			var id_hora = $(this).data('idhora');
			var dia = $(this).data('dia');
			if ($(source).hasClass('assigned-materia')){
				var id_profesor = $(source).data('idprofesor');
				$(this).removeClass('over');				
				$(this).append(source);	
				checa_disponibilidad(id_profesor, id_grupo, id_hora, dia, this);
				
			}else{				
				$(this).addClass('ocupado');
				$(this).removeClass('over');				
				var c = $(source).clone().addClass('assigned-materia');				
				$(this).empty().append(c);
				c.draggable({ revert:true });
				var id_profesor = $(this).find('a').data('idprofesor');				
				checa_disponibilidad(id_profesor, id_grupo, id_hora, dia, this);
				
			}
		}
	});
	
	$('.elimina').droppable({
		accept:aceptadas(),
		onDragEnter:function(e,source){			
			//console.log(source);			
			$(source).draggable('options').cursor='auto';
			$(source).draggable('proxy').css('border','1px solid red');
			$(this).addClass('bote-rojo');
		},
		onDragLeave:function(e,source){
			//console.log('onDragLeave');
			$(source).draggable('options').cursor='not-allowed';
			$(source).draggable('proxy').css('border','1px solid #000');
			$(this).removeClass('bote-rojo');
		},
		onDrop:function(e,source){			
			$(this).removeClass('bote-rojo');			
			$(this).append(source);
		}    
		
	});
	
});

function aceptadas(){
	var idAceptados ="";
	$("#horario  tr").each(function(index, value) {
		var id = $(this).attr('id');	
		if(typeof id != 'undefined'){
			  $("tr#"+id+" td").each(function(index,values){
				  var materiasPermitidas = parseInt($(this).find('a').data('session'));
				  var materiasTodas =parseInt($(this).find('a').data('idprofesor'));
				  if(materiasPermitidas == materiasTodas){
					 idAceptados += "#"+$(this).find('a').attr('id')+",";
				  }
				  
			  });
		} 
	});
	var newStr = idAceptados.substring(0, idAceptados.length-1);
	return newStr;	
}
function checa_disponibilidad(id_profesor, id_grupo, id_hora, dia,elemeto_actual){	
	$.ajax({
		url: '<?php echo $this->url(array('controller' => 'APG', 'action' => 'checa'));?>',  
		async:true,
		data: 'id_profesor='+id_profesor+'&id_grupo='+id_grupo+'&id_hora='+id_hora+'&dia='+dia,
		beforeSend: function(objeto){
			$('#consola').html('Checando Disponibilidad...');
			
		},
		success: function(datos) {			
			$.each(datos, function(k,v){
				if(v.validacion == 'error'){
					bottomCenter('ATENCION',' En el grupo '+v.grupo+', de '+v.hora+' ya se encuentra asignado el profesor '+v.nombre);					
					$(elemeto_actual).find('a').css('background','red');
					$(elemeto_actual).empty();									
				}else{					
					$(elemeto_actual).find('a').css('background','#eaf2ff');
				}
			});						
		},
		contentType: "application/x-www-form-urlencoded",
		dataType: "json",
		error: function(objeto, quepaso, otroobj){
			$('#consola').html('Estas viendo esto por que fallo la peticion y el error es el siguiente '+quepaso,'error');
		},		
		timeout: 3000,
		type: "POST"
	});
}
function bottomCenter(titulo,mensaje){
	$.messager.show({
		title:titulo,
		msg:mensaje,
		showType:'slide',
		style:{
			right:'',
			top:'',
			bottom:-document.body.scrollTop-document.documentElement.scrollTop
		}
	});
}
function showLoadingScreen(mensaje){   
    $.blockUI({
        title: 'ATENCION....',
        message:  mensaje  
    }); 
}

function cargar_combo(comboActual,acction,combo_a_cargar){	
	var idCombo = $('#'+comboActual).val();
	var idProfesor = $('#profesores').val();	
	if(comboActual == 'grupos' && idProfesor != ''){		
		var firstPart = "<?php echo $this->url(array('controller' => 'APG', 'action' => 'index'));?>/?idCombo=";
		window.location.href = firstPart + idCombo+'&idProfesor='+idProfesor; 
    }else if(comboActual == 'grupos'){			
		var firstPart = "<?php echo $this->url(array('controller' => 'APG', 'action' => 'index'));?>/?idCombo=";
		window.location.href = firstPart + idCombo
	}else{		
		$.ajax({
			url: acction,  
			async:true,
			data: 'idCombo='+idCombo,
			beforeSend: function(objeto){
				$('.'+combo_a_cargar).text('Cargando....');
				
			},
			success: function(datos) {					
				$('.'+combo_a_cargar).html(datos);
				$('.'+combo_a_cargar).css('display','block');
			},
			contentType: "application/x-www-form-urlencoded",
			dataType: "html",
			error: function(objeto, quepaso, otroobj){
				$('.'+combo_a_cargar).text('Estas viendo esto por que fallo la peticion y el error es el siguiente '+quepaso,'error');
			},		
			timeout: 3000,
			type: "POST"
		});
	}
}
function genera_json(){
	var id_grupo=$('#grupos').val();	
	if(id_grupo != ''){
		var json='{';
		json+='"grupos": [';
		var contador = 1;	
		$("table tr").each(function(index, value) {				
			var id_hora = $(this).data('idhora');	
			var total_materias_por_hora = $('#horario tr#hora_'+id_hora+' td.drop a').size();
			if(typeof id_hora !='undefined'){			
				if(total_materias_por_hora > 0){
					$('#horario tr#hora_'+id_hora).addClass('assigned');
				}else if(total_materias_por_hora == 0){
					$('#horario tr#hora_'+id_hora).removeClass('assigned');
				}
			}
		});
		
		var cuenta_asignado = $('.assigned').size();
		
		json+='{';
		json+='"grupo":"'+id_grupo+'",';
		json+='"horario": [';	
		$("#horario tr").each(function(index, value){
			var id_hora = $(this).data('idhora');	
			var total_materias_por_hora = $('#horario tr#hora_'+id_hora+' td.drop a').size();
			if(typeof $(this).data('idhora') != 'undefined'){
				var id_hora = $(this).data('idhora');
				if(total_materias_por_hora >0){					
					json+='{';
					json+='"hora":'+id_hora+',';
					json+=' "dias": [';	
					$('#horario tr#hora_'+id_hora+' td.drop').each(function(indice , valor){
						var id_materia = $(this).find('a').data('idmateria');
						var id_profesor = $(this).find('a').data('idprofesor');	
						var dia = $(this).data('dia');
						json+='{';
						json+='"dia": "'+dia+'",';
						json+='"materia": '+id_materia+',';
						json+='"profesor": '+id_profesor;					
						json+='},';					
					});	
					var longitud = json.length;
					json =  json.slice(0,longitud-1);				
					json+=']';	
					if(contador < cuenta_asignado){
						json +='},';
					}else{
						json +='}';
					}
					contador++;
				}
			}
		});
		json +=']}]}';
		//console.log(json);	
		$.ajax({
		url: '<?php echo $this->url(array('controller' => 'APG', 'action' => 'guarda'));?>',  
		async:true,
		data: 'cadena='+json+'&grupo='+id_grupo,
		beforeSend: function(objeto){
			showLoadingScreen('Enviando Datos');
			
		},
		complete: function(objeto, exito){				
			$.unblockUI();
		},
		contentType: "application/x-www-form-urlencoded",
		dataType: "html",
		error: function(objeto, quepaso, otroobj){
			showLoadingScreen('Estas viendo esto por que fallo la peticion y el error es el siguiente '+quepaso,'error');
		},		
		timeout: 3000,
		type: "POST"
	});
	}else{
		alert('Selecciona un grupo...');
	}
}
</script>