<div style="background:#fafafa;padding:5px;width:900px;border:1px solid #ccc" id="mm">
    <a href="#" class="easyui-menubutton" menu="#mm1" iconCls="icon-edit">Edit</a>
    <a href="#" class="easyui-menubutton" menu="#mm2" iconCls="icon-help">Help</a>
	<a href="#" class="easyui-menubutton" menu="#lista-alumnos" iconCls="icon-book">Lista de Alumnos</a>
	<a href="#" class="easyui-menubutton" menu="#mm3" iconCls="icon-user"><?php echo Zend_Auth::getInstance()->getIdentity()->S_NOMBRE;?></a>
</div>
<div id="lista-alumnos" style="width:75px;">
	<div iconCls="icon-page-excel" onclick="lista_alumnos(<?php echo Zend_Auth::getInstance()->getIdentity()->N_DATOS_PERSONALES; ?>)">Descargar</div>
	<div iconCls="icon-page-excel">Subir</div>
</div>
<div id="mm1" style="width:150px;">
    <div iconCls="icon-undo">Undo</div>
    <div iconCls="icon-redo">Redo</div>
    <div class="menu-sep"></div>
    <div>Cut</div>
    <div>Copy</div>
    <div>Paste</div>
    <div class="menu-sep"></div>
    <div iconCls="icon-remove">Delete</div>
    <div>Select All</div>
</div>

<div id="mm2" style="width:100px;">
    <div>Help</div>
    <div>Update</div>
    <div>About</div>
</div>

<div id="mm3" style="width:50pz;">
	<div iconCls="icon-door-out">Salir</div>
</div>
<script>
	function lista_alumnos(id_profesor){
		document.location.href ="<?php echo $this->url(array('controller' => 'lista', 'action' => 'index')); ?>","_blank";
	}
</script>