DROP TABLE IF EXISTS TB_ALUMNOS CASCADE
;
CREATE TABLE TB_ALUMNOS
(
	N_ID_CLAVE VARCHAR(200) NOT NULL,
	S_NOMBRE VARCHAR(100),
	S_APELLIDO VARCHAR(200),
	D_FECHA_INGRESO TIMESTAMP,
	N_ID_GRUPO BIGINT,
	S_CALLE VARCHAR(200),
	S_NUM_EXT VARCHAR(50),
	S_NUM_INT VARCHAR(50),
	N_ID_CP BIGINT,
	N_ID_PAIS BIGINT,
	S_TELEFONO VARCHAR(50),
	S_CELULAR VARCHAR(50),
	S_CONTACTO VARCHAR(50),
	N_ID_ESTATUS BIGINT,
	S_EXTRA1 VARCHAR(50),
	S_EXTRA2 VARCHAR(50),
	S_CURP VARCHAR(50),
	PRIMARY KEY (N_ID_CLAVE)

) 
;


