<?php 
$rutaPublica =	Zend_Registry::get('config')->app->baseUrl;
?>
<div id="tabs" class="easyui-tabs" style="width:740px;height:540px">			
	<div title="Datos escuela" style="padding:10px" id="datosEscuela">		
		<table id="pg" class="easyui-propertygrid" style="width:600px"
			data-options="url:'<?php echo $this->url(array('controller'=>'Lista','action'=>'propertygrid'));?>',showGroup:true,scrollbarSize:0">
		</table>
	</div>
	<div title="Lista de control" style="padding:10px" id="listaControl">
		<table id="dg" class="easyui-datagrid" style="width:710px;height:250px" url="<?php echo $this->url(array('controller'=>'Lista','action'=>'listacontrol'));?>">
			<thead>
				<tr>			
					<th field="CURP" width="230">CURP</th>            		
					<th field="nombre" width="236">NOMBRE</th>            
					<th field="edad" width="200">EDAD</th>            		
				</tr>
			</thead>
		</table>
	</div>
	<div title="Bimestres" style="padding:10px">
		<table id="dgCalificaciones" class="easyui-datagrid" title="Segumiento de calificaciones" style="width:700px;height:250px"
				data-options="
						rownumbers:false,
						singleSelect:true,						
						url:'<?php echo $this->url(array('controller'=>'Lista','action'=>'gridpromedio'))?>',
						method:'get',
						rowStyler: rowStyler,
						onClickRow: onClickRow									
						">
			<thead data-options="frozen:true">
				<th data-options="field:'id_alumno',width:20,align:'center'">ID</th>
				<th data-options="field:'nombre_alumno',width:180">Nombre</th>
				<th data-options="field:'matricula',width:100,align:'center'">Matricula</th>				
			</thead>
			<thead>
				<tr>
					 <th data-options="field:'id_mes',width:150,align:'center',
						formatter:formatter,
                        editor:{
                            type:'combobox',
                            options:{
                                valueField:'id_mes',
                                textField:'mes_nota',
                                url:'<?php echo $this->url(array('controller'=>'Lista','action'=>'combomes'))?>',
                                required:true
                            }
                        }">Mes</th>
					<?php 
					$contador = 2;
					foreach($this->titulos as $concepto){?>					
					<th data-options="field:'nota<?php echo $contador; ?>',
						align:'center',
						width:150" 
						editor="{type:'numberbox',options:{precision:1}}"><?php echo ucfirst($concepto['concepto']).'-'.$concepto['porcentaje']; ?></th>
					<?php 
					$contador++;
					} ?>
				</tr>
			</thead>
		</table>		
		<a id="btn_guarda" href="#" class="easyui-linkbutton" data-options="iconCls:'icon-save'">Guardar</a>
		<script type="text/javascript">
        $.extend($.fn.datagrid.methods, {
            editCell: function(jq,param){
                return jq.each(function(){
                    var opts = $(this).datagrid('options');
                    var fields = $(this).datagrid('getColumnFields',true).concat($(this).datagrid('getColumnFields'));
                    for(var i=0; i<fields.length; i++){
                        var col = $(this).datagrid('getColumnOption', fields[i]);
                        col.editor1 = col.editor;
                        if (fields[i] != param.field){
                            col.editor = null;
                        }
                    }
                    $(this).datagrid('beginEdit', param.index);
                    for(var i=0; i<fields.length; i++){
                        var col = $(this).datagrid('getColumnOption', fields[i]);
                        col.editor = col.editor1;
                    }
                });
            }
        });
		var lastIndex;
		var editIndex = undefined;
		function rowStyler(index,row){
			if (row.promedio < 6){
				return 'background-color:#FA5858;color:#fff;font-weight:bold;';
			}
		}
		
		function onClickRow(index){			
			if (editIndex != index){
				if (endEditing()){
					$('#dgCalificaciones').datagrid('selectRow', index)
							.datagrid('beginEdit', index);
					editIndex = index;
				} else {
					$('#dgCalificaciones').datagrid('selectRow', editIndex);
				}
			}
			if (lastIndex != index){
				$('#dgCalificaciones').datagrid('endEdit', lastIndex);
				$('#dgCalificaciones').datagrid('beginEdit', index);
				setEditing(index);
			}
			lastIndex = index;		
			
        }
        function endEditing(){
            if (editIndex == undefined){return true}            
			if ($('#dgCalificaciones').datagrid('validateRow', editIndex)){
				var ed = $('#dgCalificaciones').datagrid('getEditor', {index:editIndex,field:'id_mes'});				
				var mesname = $(ed.target).combobox('getText');
				var idmes = $(ed.target).combobox('getValue');				
				$('#dgCalificaciones').datagrid('getRows')[editIndex]['mes_nota'] = mesname;				
				$('.datagrid-btable #datagrid-row-r2-2-'+editIndex+' td[field="id_mes"] .datagrid-cell .data_idMes').text(idmes);
				$('#dgCalificaciones').datagrid('endEdit', editIndex);			
				editIndex = undefined;
				return true;
			} else {
				return false;
			}
        }	
		function setEditing(rowIndex){
			var editor = $('#dgCalificaciones').datagrid('getEditors', rowIndex);			
			var contador = 1;			
			var total_editor = editor.length;			
			for(i = 0; i<total_editor; i++){				
				if(contador < total_editor){					
					window['nota'+contador+'Editor']= editor[i];				
					window['nota'+contador+'Editor'].target.bind('change', function(){
						calculate();
					});			
				}
				if(contador == total_editor){
					var calificacionEditor = editor[i];
				}
				contador++;	
			}			
			function calculate(){								
				var suma = 0, total = 0;
				var contador = 1;
				for(i = 0; i<total_editor; i++){					
					if(contador < total_editor){
						window['nota'+contador+'Editor']= editor[i]; 
						if(window['nota'+contador+'Editor'].target.val() != ''){														
							selector = $("#datagrid-row-r2-2-0 td[field]:eq("+i+")");							
							campo = selector.attr("field");							
							separa = campo.split("-");
							porcentaje = parseFloat(separa[1]);
							suma = suma + (parseFloat(window['nota'+contador+'Editor'].target.val())) * (porcentaje);
							//console.log(suma);
						}	
					}
					if(contador == total_editor){
						var calificacionEditor = editor[i];
					}
					contador++;
				}				
				$(calificacionEditor.target).numberbox('setValue',suma);
			}
		}
		function formatter(value,row){
			return row.mes_nota+'<span style=\'display:none\' class=\'data_idMes\'>'+row.id_mes+'</span>';
		}
		
		
	</script>
	</div>
</div>
<script type="text/javascript">	
$(document).ready(function() {	
	$('#dg').datagrid({		
		method:'get',
		singleSelect:true,
		fitColumns:true,
		striped:true,
		pagination:true,
		rownumbers:true,
		sortName:"nombre",
		sortOrder:"asc",
		remoteSort:false

	});
	$('#btn_guarda').bind('click', function(){
		if (endEditing()){
			$('#dg').datagrid('acceptChanges');
		}
		var total_items = $(".datagrid-view1 > .datagrid-body > .datagrid-body-inner > .datagrid-btable > tbody > tr > td[field='nombre_alumno']").length;		
		var totalNotas = $("#datagrid-row-r2-2-0 > td").length;		
		var json ='';
		json+='[';
		for(i=0; i<total_items; i++){
			json+='{';
			$("tr#datagrid-row-r2-1-"+i+" > td[field]").each(function (indexnom, valuenom) {
				if(indexnom == 0){
					var ID = $(this).text();
					json+='"id_alumno":"'+ID+'",';
				}else if(indexnom == 1){
					var nombre = $(this).text();
					json+='"nombre":"'+nombre+'",';
				}else{
					var matricula = $(this).text();
					json+='"matricula":"'+matricula+'",';
				}			
			});
			$("tr#datagrid-row-r2-2-"+i+" td").each(function (index,value) {								
				index++;
				var valor = parseFloat($(this).text());				
				var mes = $(this).find('span').text();
				if(mes != ''){
					json+='"id_mes":'+mes+',';
				}else if(isNaN(valor)){					
					if(index < totalNotas){
						json+='"nota'+index+'":0,';			
					}else{
						json+='"nota'+index+'":0';
					}
				}else{					
					if(index < totalNotas){
						json+='"nota'+index+'":'+valor+',';			
					}else{
						json+='"nota'+index+'":'+valor;
					}
				}
				
			});

			if(i < total_items-1){
				json+='},';
			}else{
				json+='}';
			}
		}
		json+=']';	
		//console.log(json);
		$.ajax({
			url: '<?php echo $this->url(array('controller' => 'Lista', 'action' => 'guarda'));?>',  
			async:true,
			data: 'cadena='+json,
			beforeSend: function(objeto){
				showLoadingScreen('Enviando Datos');

			},
			complete: function(objeto, exito){				
				$.unblockUI();
			},
			contentType: "application/x-www-form-urlencoded",
			dataType: "html",
			error: function(objeto, quepaso, otroobj){
				showLoadingScreen('Estas viendo esto por que fallo la peticion y el error es el siguiente '+quepaso+' error');
			},		
			timeout: 3000,
			type: "POST"
		});
    });
	
	
});

function showLoadingScreen(mensaje){   
    $.blockUI({
        title: 'ATENCION....',
        message:  mensaje  
    }); 
}
</script>