<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv='X-UA-Compatible' content='IE=8' />
		
		<?php			
			echo $this->headMeta()."\n";
			echo $this->headTitle()."\n";
			$this->headLink()
				->appendStylesheet($this->baseUrl().'/css/themes/default/easyui.css')
				->appendStylesheet($this->baseUrl().'/css/themes/icon.css')
				->appendStylesheet($this->baseUrl().'/960/960.css')
				->appendStylesheet($this->baseUrl().'/css/main.css');							
			echo $this->headLink()."\n";
			$this->headScript()->appendFile($this->baseUrl().'/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js')
				 ->headScript()->appendFile($this->baseUrl().'/js/src/jquery.easyui.min.js')
				 ->headScript()->appendFile($this->baseUrl().'/js/src/jquery.edatagrid.js')
				 ->headScript()->appendFile($this->baseUrl().'/js/src/datagrid-filter.js')
				  ->headScript()->appendFile($this->baseUrl().'/js/locale/easyui-lang-es.js')
				 ->headScript()->appendFile($this->baseUrl().'/js/jquery.blockUI.js')
				 ->headScript()->appendFile($this->baseUrl().'/js/utilerias.js');
			echo $this->headScript()."\n";  
		?>
		<script>
		function genera_matricula(){
			var matricula = '';			
			matricula += 'A'+new Date().getTime();
			return matricula;
		}
				
		$(function(){
			$.extend($.fn.validatebox.defaults.rules, {				 
			    maxLength: {  
			        validator: function(value, param){				        
			            return value.length <= param[0];			              
			        },  
			        message: 'Introduzca maximo {0} carateres.'
			    },
			    telefono: {  
			        validator: function(value){
			            var expresion=/^([\+][0-9]{1,3}[ \.\-])?([\(]{1}[0-9]{2,6}[\)])?([0-9 \.\-\/]{3,20})((x|ext|extension)[ ]?[0-9]{1,4})?$/
			            return expresion.test(value);
			        },
			        message: 'N\u00famero de tel\u00e9fono no valido.'			         
				},
				soloNumeros: {  
			        validator: function(value){
			            var expresion=/^[0-9\ ]+$/
			            return expresion.test(value);
			        },
			        message: 'N\u00famero no valido.'			         
				},
				soloLetras:{
					validator: function(value){
						  var expresion=/^[a-zA-Z\ \']+$/
					      return expresion.test(value);
					},
					message :'S\u00f3lo letras'
				},
				numeros :{ //incluidos positivos y negativos
					validator: function(value){
						  var expresion=/^[\-\+]?((([0-9]{1,3})([,][0-9]{3})*)|([0-9]+))?([\.]([0-9]+))?$/ 
					      return expresion.test(value);
					},
					message :'No es un valor decimal v\u00e1lido'
				},
				codigoPostal:{
					validator: function(value){
						  var expresion=/^([0-9]{2}|[0-9][1-9]|[1-9][0-9])[0-9]{3}$/ 
					      return expresion.test(value);
					},
					message :'No es un C.P. v\u00e1lido'
				}
			});	
		});		
	</script>
	
	</head>
	<body>
		<div id="grid" class="container_12">		
	   		<?php echo $this->layout()->content; ?>
	   	</div>
	</body>
</html>